#!/bin/bash
                                                                                
mysql -u root -psecret whisky -e \
'SELECT BRANDS.BNAME, REGION.RNAME FROM BRANDS,REGION
   WHERE REGION.REGION_ID = BRANDS.REGION_ID 
   ORDER BY BRANDS.BNAME;' \
| less
                                                                                

